version: '3.8'

services:
  fraud-detection-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraud-detection-service
    ports:
      - "4000:4000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:4000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - fraud-detection-network
    # Optional: Mount volume for logs
    volumes:
      - ./logs:/app/logs

networks:
  fraud-detection-network:
    driver: bridge
